# Generated by Django 4.2.20 on 2025-04-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('book_one', models.CharField(max_length=50)),
                ('book_two', models.CharField(max_length=50)),
                ('book_three', models.CharField(max_length=50)),
                ('book_one_count', models.IntegerField(default=0)),
                ('book_two_count', models.IntegerField(default=0)),
                ('book_three_count', models.IntegerField(default=0)),
            ],
        ),
    ]
