# Generated by Django 4.2.20 on 2025-04-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='question',
        ),
        migrations.AlterField(
            model_name='poll',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
