# Generated by Django 4.2.20 on 2025-04-19 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_poll_question_alter_poll_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Poll',
        ),
    ]
