# Generated by Django 4.2.20 on 2025-04-19 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookchat', '0005_remove_book_readers'),
        ('polls', '0003_delete_poll'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('book_one_count', models.IntegerField(default=0)),
                ('book_two_count', models.IntegerField(default=0)),
                ('book_three_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('voting', 'Voting'), ('results', 'Results')], default='voting', max_length=100)),
                ('book_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_book_one', to='bookchat.book')),
                ('book_three', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_book_three', to='bookchat.book')),
                ('book_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_book_two', to='bookchat.book')),
                ('bookclub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookchat.bookclub')),
            ],
        ),
    ]
