# Generated by Django 4.2.20 on 2025-04-20 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookchat', '0005_remove_book_readers'),
        ('polls', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='bookclub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='bookchat.bookclub'),
        ),
    ]
