# Generated by Django 4.2.20 on 2025-05-01 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookchat', '0005_remove_book_readers'),
        ('polls', '0005_alter_poll_bookclub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='book_one',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='book_one_count',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='book_three',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='book_three_count',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='book_two',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='book_two_count',
        ),
        migrations.CreateModel(
            name='PollChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookchat.book')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_choices', to='polls.poll')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='polls.pollchoice')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_votes', to='polls.poll')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'poll')},
            },
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vote_count', models.IntegerField(default=0)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_results', to='polls.pollchoice')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_results', to='polls.poll')),
            ],
            options={
                'unique_together': {('poll', 'choice')},
            },
        ),
    ]
