# Generated by Django 5.1.2 on 2024-11-04 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('birth_year', models.IntegerField()),
                ('death_year', models.IntegerField()),
                ('languages', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('authors', models.ManyToManyField(related_name='my_authors', to='bookchat.author')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='titles',
            field=models.ManyToManyField(related_name='my_books', to='bookchat.book'),
        ),
    ]
