# Generated by Django 4.2.16 on 2025-01-21 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookchat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='languages',
            new_name='links',
        ),
        migrations.AddField(
            model_name='author',
            name='bio',
            field=models.TextField(default='No bio available'),
        ),
        migrations.AddField(
            model_name='book',
            name='ISBN_Identifiers',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='book',
            name='averageRating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='categories',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, default='No description available'),
        ),
        migrations.AddField(
            model_name='book',
            name='imageLinks',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='book',
            name='pageCount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, default='Unknown Publisher', max_length=128),
        ),
        migrations.AddField(
            model_name='book',
            name='ratingsCount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='birth_year',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='author',
            name='death_year',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.RemoveField(
            model_name='book',
            name='genres',
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='title_id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre_name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AddField(
            model_name='book',
            name='genres',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookchat.genre'),
        ),
    ]
