# Generated by Django 4.2.20 on 2025-03-19 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookchat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='titles',
            new_name='books',
        ),
        migrations.RenameField(
            model_name='bookshelf',
            old_name='titles',
            new_name='books',
        ),
    ]
