# Generated by Django 4.2.20 on 2025-04-13 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookchat', '0002_rename_titles_author_books_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitation',
            old_name='invited_by',
            new_name='invitee',
        ),
        migrations.RenameField(
            model_name='invitation',
            old_name='invited_user',
            new_name='inviter',
        ),
    ]
