# Generated by Django 4.2.16 on 2025-01-21 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookchat', '0004_remove_author_birth_year_remove_author_death_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
