# Generated by Django 4.2.20 on 2025-04-13 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookchat', '0004_alter_invitation_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='readers',
        ),
    ]
