# Generated by Django 4.2.16 on 2025-01-22 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookchat', '0006_alter_author_author_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='book',
            name='categories',
        ),
    ]
