# Generated by Django 4.2.16 on 2025-02-01 15:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookchat', '0007_remove_book_authors_remove_book_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='readers',
            field=models.ManyToManyField(blank=True, null=True, related_name='readers', to=settings.AUTH_USER_MODEL),
        ),
    ]
