# Generated by Django 4.2.16 on 2025-02-07 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookchat', '0009_alter_book_readers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='titles',
            field=models.ManyToManyField(related_name='author', to='bookchat.book'),
        ),
        migrations.CreateModel(
            name='Bookshelf',
            fields=[
                ('bookshelf_id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('titles', models.ManyToManyField(related_name='books', to='bookchat.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
