# Generated by Django 4.2.16 on 2025-02-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookchat', '0010_alter_author_titles_bookshelf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookshelf',
            name='titles',
            field=models.ManyToManyField(blank=True, null=True, related_name='books', to='bookchat.book'),
        ),
    ]
