# Generated by Django 4.2.16 on 2025-02-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookchat', '0011_alter_bookshelf_titles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookshelf',
            name='titles',
            field=models.ManyToManyField(related_name='books', to='bookchat.book'),
        ),
    ]
