# Generated by Django 4.2.16 on 2025-02-09 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookchat', '0012_alter_bookshelf_titles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookclub',
            fields=[
                ('bookclub_id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('administrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrator', to=settings.AUTH_USER_MODEL)),
                ('bookshelves', models.ManyToManyField(blank=True, null=True, related_name='bookshelves', to='bookchat.bookshelf')),
                ('currentRead', models.ManyToManyField(blank=True, null=True, to='bookchat.book')),
                ('members', models.ManyToManyField(related_name='members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
