# Generated by Django 4.2.16 on 2025-02-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookchat', '0013_bookclub'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookclub',
            name='isPrivate',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bookclub',
            name='bookshelves',
            field=models.ManyToManyField(blank=True, related_name='bookshelves', to='bookchat.bookshelf'),
        ),
        migrations.AlterField(
            model_name='bookclub',
            name='currentRead',
            field=models.ManyToManyField(blank=True, to='bookchat.book'),
        ),
    ]
