# Generated by Django 4.2.16 on 2025-02-12 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookchat', '0015_alter_bookclub_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookclub',
            name='currentRead',
        ),
        migrations.AddField(
            model_name='bookclub',
            name='currentRead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookchat.book'),
        ),
    ]
