# Generated by Django 4.2.16 on 2025-02-12 20:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookchat', '0016_remove_bookclub_currentread_bookclub_currentread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookclub',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, related_name='bookclubs', to=settings.AUTH_USER_MODEL),
        ),
    ]
