# Generated by Django 4.2.16 on 2025-02-25 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookchat', '0020_alter_bookshelf_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookclub',
            name='bookshelves',
            field=models.ManyToManyField(blank=True, related_name='bookclub', to='bookchat.bookshelf'),
        ),
    ]
