# Generated by Django 4.2.16 on 2025-02-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookchat', '0021_alter_bookclub_bookshelves'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_photos',
            field=models.JSONField(default=list),
        ),
    ]
