# Generated by Django 5.1.6 on 2025-02-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookchat', '0022_author_author_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_photos',
            field=models.TextField(blank=True, null=True),
        ),
    ]
