# Generated by Django 5.1.6 on 2025-02-26 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookchat', '0023_alter_author_author_photos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='author_photos',
            new_name='author_photo',
        ),
    ]
