# Generated by Django 4.2.16 on 2025-03-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookchat', '0024_rename_author_photos_author_author_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookshelf',
            name='titles',
            field=models.ManyToManyField(related_name='bookshelves', to='bookchat.book'),
        ),
    ]
