# Generated by Django 4.2.16 on 2025-03-05 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookchat', '0026_alter_bookshelf_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookclub',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
